### ISSUE TITLE
Sierra?

### ISSUE THREAD

**Issue by Multiforge** [robberize/Gigabyte-Z77N-WiFi-Hackintosh-DSDT#2]
Just wondering if this works with Sierra?

BTW, Thanks for distributing your DSDT!
I'm currently building my first Clover hackintosh around my old Z77N-WIFI board, fingers crossed.

**Comment by heyogrady** [comment]
@Multiforge did you have any problems installing Sierra using this patch?

**Comment by robberize** [comment]
Sorry everyone for the super late reply. I'm sure you've figure out by now that this DSDT patch works with macOS Sierra.
